name: Tests
on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'ci-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   testsuite:
      strategy:
         fail-fast: false
         matrix:
            c_library: [glibc, musl]
            c_compiler: [gcc, clang]
            include:
               - c_library: glibc
                 void_image: ghcr.io/void-linux/void-glibc-full:20230830r1

               - c_library: musl
                 void_image: ghcr.io/void-linux/void-musl-full:20230830r1

      runs-on: ubuntu-latest
      container: ${{ matrix.void_image }}
      steps:
         - uses: actions/checkout@v1
         - name: Prepare container
           run: |
            xbps-install -Syu || xbps-install -yu xbps
            xbps-install -Sy ${{ matrix.c_compiler }} ${{ matrix.extra_deps }} make pkg-config zlib-devel openssl-devel libarchive-devel kyua atf-devel
         - name: Build
           env:
              CC: ${{ matrix.c_compiler }}
           run: |
              ./configure --enable-tests
              make -j
         - name: Check
           run: make check
