# based on https://github.com/ruby/actions-coverity-scan/blob/282dd059/.github/workflows/coverity-scan.yml
name: coverity-scan
on:
  schedule:
    - cron: '0 18 * * *' # Daily at 18:00 UTC
  workflow_dispatch:

jobs:
  latest:
    if: github.repository == 'void-linux/xbps'
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-glibc-full:20230830r1
    env:
      TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: Updating and installing packages
        run: |
         xbps-install -Suy xbps; xbps-install -Suy
         xbps-install -Sy gcc make pkgconf kyua zlib-devel libarchive-devel atf-devel curl

      - name: Download Coverity Build Tool
        run: |
          curl -L -o cov-analysis-linux64.tar.gz --data "token=$TOKEN&project=void-linux%2Fxbps" https://scan.coverity.com/download/linux64
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64


      - name: Configure and build
        run: |
          CC=gcc ./configure --enable-tests
          PATH=$PWD/cov-analysis-linux64/bin:$PATH cov-build --dir cov-int make -j$(nproc)

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf xbps.tgz --ignore-failed-read cov-int
          curl \
            --form project=xbps \
            --form token=$TOKEN \
            --form email=github@voidlinux.org \
            --form file=@xbps.tgz \
            --form version=trunk \
            --form description="github action coverity scan" \
            https://scan.coverity.com/builds?project=void-linux%2Fxbps
